pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'kpkgkmqpetnnmod21mlmsdjlsmdks', 
                url: 'https://github.com/krishnakala987-byte/devops-mastery-journey',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo "Build Docker Image"
                    docker build -t krishna2915/todo-app:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo "Push to DockerHub"
                    docker push krishna2915/todo-app:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'kpkgkmqpetnnmod21mlmsdjlsmdks', 
                url: 'https://github.com/krishnakala987-byte/devops-mastery-journey',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(
                        credentialsId: 'kpkgkmqpetnnmod21mlmsdjlsmdks', 
                        passwordVariable: 'GIT_PASSWORD', 
                        usernameVariable: 'GIT_USERNAME'
                    )]) {
                        sh '''
                        echo "Updating deployment image tag"

                        cat deploy/deploy.yaml

                        sed -i "s/:1/:${BUILD_NUMBER}/g" deploy/deploy.yaml

                        cat deploy/deploy.yaml

                        git config user.name "jenkins"
                        git config user.email "jenkins@example.com"

                        git add deploy/deploy.yaml
                        git commit -m "Updated image to build ${BUILD_NUMBER}" || echo "No changes to commit"

                        git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/krishnakala987-byte/devops-mastery-journey.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
